### ISSUE TITLE
Feature: update & build redis version automatically in repo

### ISSUE THREAD

**Issue by hazcod** [ironPeakServices/iron-redis#2]
We currently have to manually change the redis version, which is unwanted chore work.
Better would be to have this dynamically extracted from the Redis latest image.

**Comment by hazcod** [comment]
The redis version is now automatically fetched out of `redis:latest`, but I still need to find a way to get this to build & push daily.

**Comment by AmauryOrtega** [comment]
Ideally this should be a webhook in the oficial resis image. I know there
are docker images with the only purpose of figuring out if a base image
changes in a registry and update containers in a swarm or kubernetes
cluster.

**Comment by hazcod** [comment]
@AmauryOrtega I get your idea, but I don't think the `redis` repo will be adding webhooks for every project using their base image. 
Perhaps I can use the new Github Actions and schedule it to run every day, but the documentation currently is still lacking (for the new YAML syntax).

**Comment by AmauryOrtega** [comment]
@hazcod What about Dependabot? GitHub offers it in the marketplace for free and has great integration with the new security fixes feature in GitHub.

- [Dependabot source code](https://github.com/dependabot/dependabot-core)
- [Dependabot in the marketplace](https://github.com/marketplace/dependabot-preview)
- [How to configure automates security fixes](https://help.github.com/en/articles/configuring-automated-security-fixes)

This solution is completely dependant on GitHub but it's good for now

**Comment by hazcod** [comment]
Ahhh, wait that's actually a fine idea combined with my latest commit!

- hard-code the Redis image version in the Dockerfile
- PRs are automatically opened by Dependabot with the new redis version
- Github action should release a new tagged image on PR merge

Sounds good? I wonder how to get the redis version into the Github Action.

**Comment by AmauryOrtega** [comment]
@hazcod Well, You can use awk, grep or sed to obtain the redis version from the Dockerfile using a regex.

This would be my solution: `sed --silent --expression 's/^.*redis://p' Dockerfile`.

This will print only the tag version of the first match that starts with `redis:`

**Comment by hazcod** [comment]
Fixed in https://github.com/ironPeakServices/iron-redis/commit/a905f61f18e863d1157b76209120e51e02a3b13a
