### ISSUE TITLE
Pin apt packages and indentation in Dockerfile

### ISSUE THREAD

**Issue by AmauryOrtega** [ironPeakServices/iron-redis#8]
First of all, great work with the GitHub Actions!

Here are 2 recommendations:

* Pinning apt packages.
* Follow "standard" indentation when installing packages in Dockerfiles.

Pinning versions is overkill but it might be good to think about it since it might go in line with the goal of this image. Some bash could obtain the latests version of packages and provide a PR with only those lines changed in the Dockerfile. Really similar how dependabot works I think.

The indentation is a thing I've seen in multiple official docker images on DockerHub. I think it looks more readable but it's up to you what you think. Here are some examples of it:

* [Oficial redis image](https://github.com/docker-library/redis/blob/6ec0ad5628df2404509f776e9c70fbecf5364c10/5.0/Dockerfile#L13)
* [Oficial Python image](https://github.com/docker-library/python/blob/0ecd42b0e0b519259224959b8f9dc64e76d5a73e/3.8/buster/Dockerfile#L17)
* [Oficial Ruby image](https://github.com/docker-library/ruby/blob/5c9e21cbf79b7f36d505555c9ecd62cf0f7e07f8/2.6/buster/Dockerfile#L21)

In the `redistemp` stage in the Dockerfile some packages are installed [here](https://github.com/ironPeakServices/iron-redis/blob/master/Dockerfile#L27).

```dockerfile
RUN apt-get -q update \
    && apt-get -q install -y --no-install-recommends ca-certificates wget make tcl gcc libjemalloc-dev libc6-dev
```

```dockerfile
RUN apt-get update -y \
    && apt-get -q install -y --no-install-recommends \
        ca-certificates=20180409 \
        wget=1.19.4-1ubuntu2.2 \
        make=4.1-9.1ubuntu1 \
        tcl=8.6.0+9 \
        gcc=4:7.4.0-1ubuntu2.3 \
        libjemalloc-dev=3.6.0-11 \
        libc6-dev=2.27-3ubuntu1
```

**Comment by hazcod** [comment]
Thank you for the suggestions @AmauryOrtega !
While I do get the purpose of pinning package versions completely, I'm not sure how to handle the updates of the packages automatically.

For redis, this is done automatically by upping the redis image tag by dependabot in a PR.
I suppose I could pin the package versions and see when the PR fails, in which. case I need to manually fix the new(er) package versions. What do you think?
